# single char aliases
alias a='alias'
alias d='ls -lF'
alias h='history'
alias z='ls -aF'

# misc aliases
alias bc='bc -l'
alias cls='clear'
alias ealias='vim ~/settings/bash_aliases'
alias salias='source ~/settings/bash_aliases'
alias md='mkdir'
alias rd='rmdir'
alias psu='ps -f -u $USER'
alias psu2='ps -f -u $USER -U $USER'
alias psuj='ps -f -u $USER | grep java'
alias ssh-forward-port-example='ssh -L local_port:remote_host:remote_port'
alias vimcr='vim -b'

# Git aliases
alias gbd='git branch --delete'
alias gbr='git branch'
alias gchmod-x='git update-index --chmod=-x'
alias gchmodx='git update-index --chmod=+x'
alias gcb='git checkout -b'
alias gclist='git config --list --show-origin'
alias gci='git commit'
alias gco='git checkout'
alias gdi='git diff'
alias gfe='git fetch'
alias gfp='git fetch --prune'
alias glg='git log --graph --decorate'
alias glg1='git log --graph --decorate --oneline'
alias glg2='git log --graph --pretty=format:"%C(auto)%h -%d %s %Cgreen(%cd) %C(bold blue)<%an>%Creset" --date=format:%c'
alias glo='git log'
alias gpfs='git push --force-with-lease'
alias gpr='git pull --rebase --prune'
alias gpu='git pull'
alias gpush='git push --set-upstream origin HEAD'
alias gsl='git stash list'
alias gsp='git stash pop'
alias gss='git stash'
alias gst='git status'
alias gsv='git stash show'
alias gsvv='git stash show -v'
alias gsv1='git stash show stash@{1}'
alias gsv2='git stash show stash@{2}'

# Gradle aliases
alias gr='gradle'
alias grb='gradle build'
alias grc='gradle clean'
alias grcb='gradle clean build'
alias grp2local='gradle publishToMavenLocal'
alias gw='./gradlew'
alias gw..='../gradlew'
alias gwb='gw build'
alias gwb..='gw.. build'
alias gwc='gw clean'
alias gwcb='gw clean build'
alias gwd='gw dependencies'
alias gwdm='gw dependencyManagement'
alias gwp2local='gw publishToMavenLocal'
alias gwupgrade-example='gw wrapper --gradle-version 4.10 --gradle-distribution-sha256-sum 248cfd92104ce12c5431ddb8309cf713fe58de8e330c63176543320022f59f18; gw wrapper -v'

